### ISSUE TITLE
does not

### ISSUE THREAD

**Issue by ghost** [ManRueda/jade-autocompile#21]
it does not compile on save.

when is it supposed to?

**Comment by manrueda** [comment]
Hi, can you give me more information to try to recreate it.

Atom version, you configuration comment and maybe an jade code example.

Thanks!

**Comment by ghost** [comment]
Hi, Atom 1.8, on osx latest, also let me know anything else, I'd love to be
able to get it to work. Here is just simplest jade:

p.
  oh hi

**Comment by manrueda** [comment]
Mhhh can you send me your comment config? Because is working for me...

**Comment by ghost** [comment]
I'm happy to hear that it can work. Please help.
Here is the file:
"_":
  "atom-idle-autosave":
    debounce: 2500
  autosave:
    enabled: true
  "browser-refresh":
    googleChromeCanary: true
  core:
    disabledPackages: [
      "chrome-color-picker"
      "jade-beautify"
      "linter-jade"
      "autocompile-jade"
      "jade-autocompile"
      "browser-plus"
      "browser-refresh-on-save"
    ]
    ignoredNames: [
      "._"
      "_.map"
      "_.css"
      "_.dist.js"
      "_.jpg"
      "*.html"
    ]
  editor:
    backUpBeforeSaving: true
    fontSize: 15
    showIndentGuide: true
    softWrap: true
  "exception-reporting":
    userId: "269718f1-a82c-51c4-e87c-e3c643098288"
  "jade-beautify":
    BEAUTIFY_ON_SAVE: true
    BEAUTIFY_ON_SAVE_ALL: true
  preview:
    _analyticsUserId: "145730b3-2a48-4a9c-9d16-fa1c2271ba4c"
  "tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
  welcome:
    showOnStartup: false

**Comment by manrueda** [comment]
No, look the README.md file, you need to put a comment in the first lines to make it work. I need those comments.

**Comment by ghost** [comment]
I'm sorry, I'm not able to follow. I installed your project via 'atom gui
install'. There is no config there.
I'm now reading the read me file on home page of git and I don't
understand, not even the first line. 'The two first comment blocks of file
can be used to pass parameters to the compiler.'
I have installed other atom packages w/o a problem, like auto save, or f5
for browser refresh, they work.

Where would such a comment block be?
Here is what I see, just so you can see how lost I am.
help.
[image: Inline image 1]

**Comment by manrueda** [comment]
The README file can be accessed by Atom's Package Installer. Atom uses the README file as a "front-page" for each package.

This package require to put a comment in the jade file to be compiled. This comment will tell to the package the location to put the html file, the name and other things.

I hope that this will clarify your doubts.

**Comment by ghost** [comment]
Got it. (other things had a gui config. It seems odd to edit a readme file).

So still no joy, I edited like so, just removed the comment:

# jade-autocompile package [![Build Status](

https://travis-ci.org/ManRueda/jade-autocompile.svg?branch=master)](https://travis-ci.org/ManRueda/jade-autocompile
)

Auto compile JADE files on save

[Atom package site](https://atom.io/packages/jade-autocompile)

## Configuration

The two first comment blocks of file can be used to pass parameters to the
compiler.
- The first one must have the name of the output html file, like this:
  
  ``` jade
  output:$1.html
  ```
  
  If you avoid this comment, the file is omitted by the compiler.

**Comment by manrueda** [comment]
No, you don't need to edit the README file, you need to edit your jade file. With the comment as the example in the README

**Comment by ghost** [comment]
Oh. OK. It works!

I would have docs say this, instead of Configuration, since there is no
Configuration:
" To compile, your jade file must have comments in the first line like
this:
...."

THANK YOU! Nice plug in.
Vic
