### ISSUE TITLE
Cannot apply transform markdown

### ISSUE THREAD

**Issue by DizzyZane** [ManRueda/jade-autocompile#9]
Have been looking around for `markdown-js` and whilst I have found it (https://github.com/evilstreak/markdown-js) and attempted to install it to the best of my abilities, the compiler still throws an error:

```
In order to apply the transform markdown you must install one of "marked","supermarked","markdown-js","markdown"
```

I have restarted my PC (and therefore the programme) and I had installed it whilst it was not running.

How would I install it?

**Comment by manrueda** [comment]
Hi @DizzyZane, i don't know why are making this question here... markdown-js  has no relation with jade or this plugin.
Jade it's for compile jade to html and you are trying to compile markdown to html.

I'm going to close the issue for now.

**Comment by DizzyZane** [comment]
Ah. Well uhhh... how would I install `markdown-js` such that it functions with `jade-autocompile`?

**Comment by manrueda** [comment]
Really i don't know, you should search here https://atom.io/packages/, maybe there is a package for that... but i don't know.

**Comment by DizzyZane** [comment]
Needed to install node and `npm i jstransformer-markdown` (alternatively I used `npm i jstransformer-marked` and switched to :marked.

Thank you anyway.
